// <auto-generated />
using System;
using ExquisiteCorpseAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExquisiteCorpseAPI.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260215202736_Genders")]
    partial class Genders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("ExquisiteCorpseAPI.Models.Adjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GenderId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("LanguageId", "Text")
                        .IsUnique();

                    b.ToTable("adjectives", (string)null);
                });

            modelBuilder.Entity("ExquisiteCorpseAPI.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("genders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Neutral"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Male"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Female"
                        });
                });

            modelBuilder.Entity("ExquisiteCorpseAPI.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Acronym")
                        .IsUnique();

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("ExquisiteCorpseAPI.Models.ObjectWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId", "Text")
                        .IsUnique();

                    b.ToTable("objectWords", (string)null);
                });

            modelBuilder.Entity("ExquisiteCorpseAPI.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GenderId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("LanguageId", "Text")
                        .IsUnique();

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("ExquisiteCorpseAPI.Models.Verb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId", "Text")
                        .IsUnique();

                    b.ToTable("verbs", (string)null);
                });

            modelBuilder.Entity("ExquisiteCorpseAPI.Models.Adjective", b =>
                {
                    b.HasOne("ExquisiteCorpseAPI.Models.Gender", "Gender")
                        .WithMany("Adjectives")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExquisiteCorpseAPI.Models.Language", "Language")
                        .WithMany("Adjectives")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("ExquisiteCorpseAPI.Models.ObjectWord", b =>
                {
                    b.HasOne("ExquisiteCorpseAPI.Models.Language", "Language")
                        .WithMany("ObjectWords")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("ExquisiteCorpseAPI.Models.Subject", b =>
                {
                    b.HasOne("ExquisiteCorpseAPI.Models.Gender", "Gender")
                        .WithMany("Subjects")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExquisiteCorpseAPI.Models.Language", "Language")
                        .WithMany("Subjects")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("ExquisiteCorpseAPI.Models.Verb", b =>
                {
                    b.HasOne("ExquisiteCorpseAPI.Models.Language", "Language")
                        .WithMany("Verbs")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("ExquisiteCorpseAPI.Models.Gender", b =>
                {
                    b.Navigation("Adjectives");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("ExquisiteCorpseAPI.Models.Language", b =>
                {
                    b.Navigation("Adjectives");

                    b.Navigation("ObjectWords");

                    b.Navigation("Subjects");

                    b.Navigation("Verbs");
                });
#pragma warning restore 612, 618
        }
    }
}
